# The config file for perturbations
rdmPert:  # random connections
    data_name: cora  # cora/citeseer/pubmed/amazoncobuy/coauthor
    model_name: GCN
    TARGET_CLASS: -1
    SAMPLE_RATE: 0.1  # [0.1, 0.1, 0.1, 0.99, 0.1]
    GPU: 0
infoSparse:  # information sparsity
    data_name: cora
    model_name: GCN
    TARGET_CLASS: -1
    SAMPLE_RATE: 1.0
    GPU: 0
advAttack:  # adversarial attacks
    data_name: cora
    model_name: GCN
    pert_type: clean  # cora/citeseer/pubmed: clean; amazoncobuy/coauthor: infoSparse.
    TARGET_CLASS: -1
    attack_type: lf  # l, f, lf
    NUM_PERT: 2
    SAMPLE_RATE: 0.1  # [0.1, 0.1, 0.02, 0.05, 0.02]
    NOISE_RATIO: 0.1
    GPU: 0
    is_attack: True  # False for prediction
